version: '2'

services:
  monacoin:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-mainnet

  monacoin-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-testnet

  counterparty:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-mainnet
    links:
      - monacoin

  counterparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-testnet
    links:
      - monacoin-testnet

volumes:
  bitcoin-data:
  counterparty-data:
